### Test root
GET http://localhost:5000/

### Test POST JSON
POST http://localhost:5006/test
Content-Type: application/json

{
  "url": "ktunotes.in"
}
###

POST http://localhost:5000/test
Content-Type: application/json

{
  "url": "google"
}